# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run test suite for hw2
      run: |
        cd src/hw2/
        coverage run test_suite.py
        coverage report
    - name: Run test suite for hw3
      run: |
        cd src/hw3/
        coverage run test_suite.py
        coverage report
    - name: Run test suite for hw4
      run: |
        cd src/hw4/
        coverage run test_suite.py
        coverage report
    - name: Run test suite for hw5
      run: |
          cd src/hw5/
          coverage run test_suite.py
          coverage report
    - name: Run test suite for hw6
      run: |
          cd src/hw6/
          coverage run test_suite.py
          coverage report 
    - name: Run test suite for hw7
      run: |
          cd src/hw7/
          coverage run test_suite.py
          coverage report
    - name: Run test suite for hw8
      run: |
          cd src/hw8/
          coverage run test_suite.py
          coverage report
    - name: Run test suite for hw9
      run: |
          cd src/hw9/
          coverage run test_suite.py
          coverage report
